configMap:
  db_host: expense-dev.cq108m6osh9n.us-east-1.rds.amazonaws.com
deployment:
  imageURL: 945488516062.dkr.ecr.us-east-1.amazonaws.com/expense/dev/backend
  imageVersion: IMAGE_VERSION
hpa:
  cpuUtilization: 20